<?php

namespace ContainerU0mXlDc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeTicket2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.x52HXCg.App\Entity\CommandeTicket' shared service.
     *
     * @return \App\Entity\CommandeTicket
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.x52HXCg": it references class "App\\Entity\\CommandeTicket" but no such service exists.');
    }
}
