#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_utilisateur_frontend :
 path: /frontend
 controller: App\Controller\UtilisateurController::frontindex
app_utilisateur_login :
 path: /login.html
 controller: App\Controller\UtilisateurController::loginindex
send_email:
 path: /send-email
 controller: App\Controller\SecurityController::sendEmail
app_logout:
    path: /app_logout
    controller: App\Controller\SecurityController::logout
app_user:
    path: /mayar
    controller: App\Controller\UtilisateurController::showUtilisateurs
