<?php

namespace ContainerTEOWVkW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1yLvbZ8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1yLvbZ8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1yLvbZ8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'ticket' => ['privates', '.errored..service_locator.1yLvbZ8.App\\Entity\\Ticket', NULL, 'Cannot autowire service ".service_locator.1yLvbZ8": it references class "App\\Entity\\Ticket" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'ticket' => 'App\\Entity\\Ticket',
        ]);
    }
}
