<?php

namespace ContainerM1JTgxM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X52HXCgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x52HXCg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x52HXCg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commandeTicket' => ['privates', '.errored..service_locator.x52HXCg.App\\Entity\\CommandeTicket', NULL, 'Cannot autowire service ".service_locator.x52HXCg": it references class "App\\Entity\\CommandeTicket" but no such service exists.'],
        ], [
            'commandeTicket' => 'App\\Entity\\CommandeTicket',
        ]);
    }
}
