<?php

namespace ContainerM1JTgxM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeTicketService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TErqy7R.App\Entity\CommandeTicket' shared service.
     *
     * @return \App\Entity\CommandeTicket
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.TErqy7R": it references class "App\\Entity\\CommandeTicket" but no such service exists.');
    }
}
