<?php

namespace ContainerM1JTgxM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTicket2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7Txv_C4.App\Entity\Ticket' shared service.
     *
     * @return \App\Entity\Ticket
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.7Txv_C4": it references class "App\\Entity\\Ticket" but no such service exists.');
    }
}
