<?php

namespace ContainerOl3fDSA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwilioClientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TwilioClient' shared autowired service.
     *
     * @return \App\Service\TwilioClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TwilioClient.php';

        return $container->privates['App\\Service\\TwilioClient'] = new \App\Service\TwilioClient('ACe4b091c7a2f2d726989eeff24965ab56', '9b22601bdad71a4bc1607a236558c995');
    }
}
