<?php

namespace ContainerI7wQJKC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZXoHI_PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZXoHI.p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZXoHI.p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CommentaireRecController::delete' => ['privates', '.service_locator.lpWiD1Y', 'get_ServiceLocator_LpWiD1YService', true],
            'App\\Controller\\CommentaireRecController::edit' => ['privates', '.service_locator.lpWiD1Y', 'get_ServiceLocator_LpWiD1YService', true],
            'App\\Controller\\CommentaireRecController::index' => ['privates', '.service_locator.Zhsi5nT', 'get_ServiceLocator_Zhsi5nTService', true],
            'App\\Controller\\CommentaireRecController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CommentaireRecController::sendSms' => ['privates', '.service_locator.jesuEm.', 'get_ServiceLocator_JesuEm_Service', true],
            'App\\Controller\\CommentaireRecController::show' => ['privates', '.service_locator.Ad96Blr', 'get_ServiceLocator_Ad96BlrService', true],
            'App\\Controller\\ReclamationController::contactIndex' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ReclamationController::delete' => ['privates', '.service_locator.etz6_w_', 'get_ServiceLocator_Etz6WService', true],
            'App\\Controller\\ReclamationController::edit' => ['privates', '.service_locator.etz6_w_', 'get_ServiceLocator_Etz6WService', true],
            'App\\Controller\\ReclamationController::list' => ['privates', '.service_locator.bvmeD74', 'get_ServiceLocator_BvmeD74Service', true],
            'App\\Controller\\ReclamationController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ReclamationController::show' => ['privates', '.service_locator.iq_16Ky', 'get_ServiceLocator_Iq16KyService', true],
            'App\\Controller\\ReclamationController::statistique' => ['privates', '.service_locator.8lwgiB6', 'get_ServiceLocator_8lwgiB6Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\CommentaireRecController:delete' => ['privates', '.service_locator.lpWiD1Y', 'get_ServiceLocator_LpWiD1YService', true],
            'App\\Controller\\CommentaireRecController:edit' => ['privates', '.service_locator.lpWiD1Y', 'get_ServiceLocator_LpWiD1YService', true],
            'App\\Controller\\CommentaireRecController:index' => ['privates', '.service_locator.Zhsi5nT', 'get_ServiceLocator_Zhsi5nTService', true],
            'App\\Controller\\CommentaireRecController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CommentaireRecController:sendSms' => ['privates', '.service_locator.jesuEm.', 'get_ServiceLocator_JesuEm_Service', true],
            'App\\Controller\\CommentaireRecController:show' => ['privates', '.service_locator.Ad96Blr', 'get_ServiceLocator_Ad96BlrService', true],
            'App\\Controller\\ReclamationController:contactIndex' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ReclamationController:delete' => ['privates', '.service_locator.etz6_w_', 'get_ServiceLocator_Etz6WService', true],
            'App\\Controller\\ReclamationController:edit' => ['privates', '.service_locator.etz6_w_', 'get_ServiceLocator_Etz6WService', true],
            'App\\Controller\\ReclamationController:list' => ['privates', '.service_locator.bvmeD74', 'get_ServiceLocator_BvmeD74Service', true],
            'App\\Controller\\ReclamationController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ReclamationController:show' => ['privates', '.service_locator.iq_16Ky', 'get_ServiceLocator_Iq16KyService', true],
            'App\\Controller\\ReclamationController:statistique' => ['privates', '.service_locator.8lwgiB6', 'get_ServiceLocator_8lwgiB6Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\CommentaireRecController::delete' => '?',
            'App\\Controller\\CommentaireRecController::edit' => '?',
            'App\\Controller\\CommentaireRecController::index' => '?',
            'App\\Controller\\CommentaireRecController::new' => '?',
            'App\\Controller\\CommentaireRecController::sendSms' => '?',
            'App\\Controller\\CommentaireRecController::show' => '?',
            'App\\Controller\\ReclamationController::contactIndex' => '?',
            'App\\Controller\\ReclamationController::delete' => '?',
            'App\\Controller\\ReclamationController::edit' => '?',
            'App\\Controller\\ReclamationController::list' => '?',
            'App\\Controller\\ReclamationController::new' => '?',
            'App\\Controller\\ReclamationController::show' => '?',
            'App\\Controller\\ReclamationController::statistique' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CommentaireRecController:delete' => '?',
            'App\\Controller\\CommentaireRecController:edit' => '?',
            'App\\Controller\\CommentaireRecController:index' => '?',
            'App\\Controller\\CommentaireRecController:new' => '?',
            'App\\Controller\\CommentaireRecController:sendSms' => '?',
            'App\\Controller\\CommentaireRecController:show' => '?',
            'App\\Controller\\ReclamationController:contactIndex' => '?',
            'App\\Controller\\ReclamationController:delete' => '?',
            'App\\Controller\\ReclamationController:edit' => '?',
            'App\\Controller\\ReclamationController:list' => '?',
            'App\\Controller\\ReclamationController:new' => '?',
            'App\\Controller\\ReclamationController:show' => '?',
            'App\\Controller\\ReclamationController:statistique' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
