<?php

namespace ContainerI7wQJKC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LpWiD1YService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lpWiD1Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lpWiD1Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentaireRec' => ['privates', '.errored..service_locator.lpWiD1Y.App\\Entity\\CommentaireRec', NULL, 'Cannot autowire service ".service_locator.lpWiD1Y": it references class "App\\Entity\\CommentaireRec" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'commentaireRec' => 'App\\Entity\\CommentaireRec',
            'entityManager' => '?',
        ]);
    }
}
