<?php

namespace ContainerI7wQJKC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JesuEm_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jesuEm.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jesuEm.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentaireRecType' => ['privates', 'App\\Form\\CommentaireRecType', 'getCommentaireRecTypeService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'twilioClient' => ['privates', 'App\\Service\\TwilioClient', 'getTwilioClientService', true],
        ], [
            'commentaireRecType' => 'App\\Form\\CommentaireRecType',
            'entityManager' => '?',
            'twilioClient' => 'App\\Service\\TwilioClient',
        ]);
    }
}
