<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI7wQJKC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI7wQJKC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI7wQJKC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI7wQJKC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI7wQJKC\App_KernelDevDebugContainer([
    'container.build_hash' => 'I7wQJKC',
    'container.build_id' => '7d07a757',
    'container.build_time' => 1682477177,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI7wQJKC');
