<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6U5AX2T\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6U5AX2T/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6U5AX2T.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6U5AX2T\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6U5AX2T\App_KernelDevDebugContainer([
    'container.build_hash' => '6U5AX2T',
    'container.build_id' => '86615fa4',
    'container.build_time' => 1682472982,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6U5AX2T');
