<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCDomo6Y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCDomo6Y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCDomo6Y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCDomo6Y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCDomo6Y\App_KernelDevDebugContainer([
    'container.build_hash' => 'CDomo6Y',
    'container.build_id' => 'ccf5bf7c',
    'container.build_time' => 1681286221,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCDomo6Y');
