<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_commande_ticket_index' => [[], ['_controller' => 'App\\Controller\\CommandeTicketController::index'], [], [['text', '/commande/ticket/']], [], [], []],
    'app_commande_ticket_new' => [[], ['_controller' => 'App\\Controller\\CommandeTicketController::new'], [], [['text', '/commande/ticket/new']], [], [], []],
    'app_commande_ticket_newF' => [[], ['_controller' => 'App\\Controller\\CommandeTicketController::newF'], [], [['text', '/commande/ticket/newF']], [], [], []],
    'app_commande_ticket_show' => [['id'], ['_controller' => 'App\\Controller\\CommandeTicketController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/commande/ticket']], [], [], []],
    'app_commande_ticket_showF' => [['id'], ['_controller' => 'App\\Controller\\CommandeTicketController::showF'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/commande/ticket/F']], [], [], []],
    'app_commande_ticket_edit' => [['id'], ['_controller' => 'App\\Controller\\CommandeTicketController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/commande/ticket']], [], [], []],
    'app_commande_ticket_editF' => [['id'], ['_controller' => 'App\\Controller\\CommandeTicketController::editF'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/commande/ticket/F']], [], [], []],
    'app_commande_ticket_delete' => [['id'], ['_controller' => 'App\\Controller\\CommandeTicketController::deleteF'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/commande/ticket']], [], [], []],
    'app_ticket_index' => [[], ['_controller' => 'App\\Controller\\TicketController::index'], [], [['text', '/ticket/']], [], [], []],
    'app_ticket_indexF' => [[], ['_controller' => 'App\\Controller\\TicketController::indexF'], [], [['text', '/ticket/F']], [], [], []],
    'app_ticket_new' => [[], ['_controller' => 'App\\Controller\\TicketController::new'], [], [['text', '/ticket/new']], [], [], []],
    'app_ticket_show' => [['id'], ['_controller' => 'App\\Controller\\TicketController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/ticket']], [], [], []],
    'app_ticket_edit' => [['id'], ['_controller' => 'App\\Controller\\TicketController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/ticket']], [], [], []],
    'app_ticket_delete' => [['id'], ['_controller' => 'App\\Controller\\TicketController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/ticket']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
];
